#!/usr/bin/env bash
# This script Install Nginx web server

# the apt_get is followed by yes to answer all the prompts
# while installing

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
