#!/usr/bin/env bash
# This script apply Redundancy for  web01 and Web02 to handle traffic and be more efficient


sudo apt-get update
sudo apt-get install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=xZIwIoekjgw;}' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' /etc/nginx/sites-available/default
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By \$HOSTNAME;/" /etc/nginx/sites-available/default
sudo service nginx restart
