#!/usr/bin/env bash
# This script is reconfugring Nginex to listen to port 8à in case it isn't
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
