#!/usr/bin/env bash
# This script is reconfugring Nginex to listen to port 80 in case it isn't
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
