#!/usr/bin/env bash
# This start the app using API
server {
    # Listen on port 80
    listen      80 default_server;
    listen      [::]:80 default_server ipv6only=on;

    server_name 52.87.254.240;

    add_header  X-Served-By 20205-web-01;

    # route on AirBnB_clone_v3
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    #  route on AirBnB_clone_v3
    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
    }

    #  API on AirBnB_clone_v3
    location /api {
        proxy_pass http://127.0.0.1:5002/api;
    }

    # 404 error page
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
