#!/usr/bin/env bash
# This script is to prevent users to be root user

chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf

# Comment out Apache's port configuration
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf

# Change the user in nginx.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Change the default port in the default site configuration
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart Apache to release port 8080
pkill -1 apache2

# Restart Nginx service
sudo -u nginx service nginx restart
